# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

OrganizationalUnitIdentifiers:
  - Certificate: "cacerts/cloudcityinc-ca-7054.pem"
    OrganizationalUnitIdentifier: "client"
  - Certificate: "cacerts/cloudcityinc-ca-7054.pem"
    OrganizationalUnitIdentifier: "peer"

NodeOUs:
  Enable: true
  ClientOUIdentifier:
    # if Certificate is empty, then the certifier identifier will not be enforced
    Certificate: "cacerts/cloudcityinc-ca-7054.pem"
    OrganizationalUnitIdentifier: "client"
  PeerOUIdentifier:
    Certificate: "cacerts/cloudcityinc-ca-7054.pem"
    OrganizationalUnitIdentifier: "peer"
