
url: https://cloudcityinc-ca:7054

mspdir: msp

# "The client option is required only if mutual TLS is configured on the server." (https://hyperledger-fabric-ca.readthedocs.io/en/latest/users-guide.html#enabling-tls)
tls:
  certfiles: /shared/cloudcityinc-root-ca-cert.pem
  client:
    certfile:
    keyfile:

csr:
  cn: cloudcityinc-ca
  serialnumber:
  names:
    - C: US
      ST: Texas
      L:
      O: TangoJLabs
      OU: client
  hosts:
    - cloudcityinc-ca

id:
  name:
  type:
  # Affiliation is not used to limit users in this sample, so just put all identities in the same affiliation.
  affiliation: cloudcityinc
  maxenrollments: 0
  attributes:
   # - name:
   #   value:

enrollment:
  profile:
  label:

caname:

bccsp:
    default: SW
    sw:
        hash: SHA2
        security: 256
        filekeystore:
            keystore: msp/keystore
