version: '2'

# The network should already exist, even if this is the first service(s) to start (see README step 0.1)
networks:
  outer_rim_trade:
    external: true

services:
  huttcorp-ca:
    container_name: huttcorp-ca
    image: hyperledger/fabric-ca
    environment:
      - COMPOSE_PROJECT_NAME=outer_rim_trade_project
      
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_CLIENT_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
      
    volumes:
      - ./:/etc/hyperledger/fabric-ca-server/setup
      # This directory map allows the CLI environment to access the passed CA crypto material:
      - ./../shared:/shared
    command: /bin/bash -c 'mkdir /shared/logs; /etc/hyperledger/fabric-ca-server/setup/ca_auto.sh 2>&1 | tee /shared/logs/ca.log; sleep 99999'
    ports:
      - 7054:7054
    networks:
      - outer_rim_trade