version: '2'

# The network should already exist, even if this is the first service(s) to start (see README step 0.1)
networks:
  outer_rim_trade:
    external: true

services:
  huttcorp-cli:
    container_name: huttcorp-cli
    image: hyperledger/fabric-ca-tools
    environment:
      - COMPOSE_PROJECT_NAME=outer_rim_trade_project
      
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric #Needed to find the configtx.yaml file for configtxgen processes
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_GRPC=DEBUG
    
    volumes:
      - ./:/etc/hyperledger/fabric/setup
      # This directory map allows the CLI environment to access the passed CA crypto material:
      - ./../shared:/shared
      # Map the directories needed for the chaincode (file and processes):
      - /Users/seanhart/go/src/github.com/hyperledger/fabric:/opt/gopath/src/github.com/hyperledger/fabric
      - ./../shared/chaincode/wallet:/opt/gopath/src/chaincode/wallet
      - ./../shared/chaincode/user:/opt/gopath/src/chaincode/user
      
    command: /bin/bash -c '/etc/hyperledger/fabric/setup/cli_auto.sh 2>&1 | tee /shared/logs/cli.log; sleep 99999'
    ports:
      - 3000:3000
    networks:
      - outer_rim_trade