# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

Organizations:
  - &org1
    Name: org1
    ID: org1MSP
    # If FABRIC_CFG_PATH is modified, change the below MSP directory
    MSPDir: /etc/hyperledger/fabric/orgs/org1/msp
    Policies: &org1Policies
        Readers:
            Type: Signature
            Rule: "OR('org1MSP.admin', 'org1MSP.peer', 'org1MSP.client')"
        Writers:
            Type: Signature
            Rule: "OR('org1MSP.admin', 'org1MSP.peer')"
        Admins:
            Type: Signature
            Rule: "OR('org1MSP.admin')"
    AnchorPeers:
       - Host: org1-peer0
         Port: 7051

Capabilities:
    Global: &ChannelCapabilities
        V1_1: true
    Orderer: &OrdererCapabilities
        V1_1: true
    Application: &ApplicationCapabilities
        V1_2: true

Application: &ApplicationDefaults
    ACLs: &ACLsDefault
      lscc/ChaincodeExists: /Channel/Application/Readers
      lscc/GetDeploymentSpec: /Channel/Application/Readers
      lscc/GetChaincodeData: /Channel/Application/Readers
      lscc/GetInstantiatedChaincodes: /Channel/Application/Readers
      qscc/GetChainInfo: /Channel/Application/Readers
      qscc/GetBlockByNumber: /Channel/Application/Readers
      qscc/GetBlockByHash: /Channel/Application/Readers
      qscc/GetTransactionByID: /Channel/Application/Readers
      qscc/GetBlockByTxID: /Channel/Application/Readers
      cscc/GetConfigBlock: /Channel/Application/Readers
      cscc/GetConfigTree: /Channel/Application/Readers
      cscc/SimulateConfigTreeUpdate: /Channel/Application/Readers
      peer/Propose: /Channel/Application/Writers
      peer/ChaincodeToChaincode: /Channel/Application/Readers
      event/Block: /Channel/Application/Readers
      event/FilteredBlock: /Channel/Application/Readers

    Organizations:
      
    Policies: &ApplicationDefaultPolicies
      Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
      Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
      Admins:
        Type: ImplicitMeta
        Rule: "ANY Admins" #"MAJORITY Admins"

    Capabilities:
      <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
      - org1-orderer:7050
    BatchTimeout: 2s
    BatchSize:
      MaxMessageCount: 10
      AbsoluteMaxBytes: 99 MB
      PreferredMaxBytes: 512 KB
    MaxChannels: 0
    Kafka:
      Brokers:
        - 127.0.0.1:9092
    
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
      Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
      Admins:
        Type: ImplicitMeta
        Rule: "ANY Admins" #"MAJORITY Admins"
      BlockValidation:
        Type: ImplicitMeta
        Rule: "ANY Writers"

    Capabilities:
      <<: *OrdererCapabilities

Channel: &ChannelDefaults
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
      Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
      Admins:
        Type: ImplicitMeta
        Rule: "ANY Admins" #"MAJORITY Admins"

    Capabilities:
      <<: *ChannelCapabilities

Profiles:
  OrgsOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *org1
    Consortiums:
      cSoloConsortium:
        Organizations:
          - *org1

  OrgsChannel:
    Consortium: cSoloConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *org1
