
url: https://org2-ca:7054

mspdir: msp

# "The client option is required only if mutual TLS is configured on the server." (https://hyperledger-fabric-ca.readthedocs.io/en/latest/users-guide.html#enabling-tls)
tls:
  certfiles: /shared/org2-root-ca-cert.pem
  client:
    certfile:
    keyfile:

csr:
  cn: org2-ca
  serialnumber:
  names:
    - C: US
      ST: State
      L:
      O: Org2
      OU: client
  hosts:
    - org2-ca

id:
  name:
  type:
  affiliation: org2
  maxenrollments: 0
  attributes:
   # - name:
   #   value:

enrollment:
  profile:
  label:

caname:

bccsp:
    default: SW
    sw:
        hash: SHA2
        security: 256
        filekeystore:
            keystore: msp/keystore
